version: '3'
services:
  rabbit-mq:
    image: rabbitmq:3-management 
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  adv-config-server:
    build: adv-config-server/
    ports:
      - "9999:8080"    