server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: file:/home/justi.andre/dev/github/workshop-microservices/sources/cloud-lab06-sol/config-repo          
  rabbitmq:
    host: localhost
    port: 5672    