server:
  port: ${PORT:${SERVER_PORT:9998}}
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
---
spring:
  profiles: adv-eureka-server1

server:
  port: 9001
  
eureka:
  instance:
    hostname: adv-eureka-server1
  client:
    serviceUrl:
      defaultZone: http://adv-eureka-server2:9002/eureka/  
  
---
spring:
  profiles: adv-eureka-server2

server:
  port: 9002
  
eureka:
  instance:
    hostname: adv-eureka-server2
  client:
    serviceUrl:
      defaultZone: http://adv-eureka-server1:9001/eureka/  